services:
  global-channel-search:
    image: ghcr.io/tw1zt3d2four7/global-channel-search:latest
    container_name: global-channel-search
    stdin_open: true
    tty: true
    restart: "no"  # <-- This stops infinite restarts
    volumes:
      - ./global-channel-search/data:/data
      - ./global-channel-search/cache:/cache
    environment:
      - TERM=xterm
