services:
  global-channel-search:
    image: ghcr.io/tw1zt3d2four7/global-channel-search:latest
    container_name: global-channel-search
    restart: unless-stopped
    ports:
      - "8000:8000"   # Change ports if your app listens on something else
    volumes:
      - ./global-channel-search/data:/data
      - ./global-channel-search/cache:/cache
    environment:
      - TERM=xterm
      
