name: Build and Push Docker Image

on:
  push:
    branches: [ main ]  # Run this workflow when you push to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Required to publish to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image with :latest tag
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/global-channel-search:latest .

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/global-channel-search:latest

